table brdg__job_skill
	lineageTag: 05577f56-5ee9-415a-9acb-777b81b25724

	column job_key
		dataType: string
		lineageTag: 0bc636fa-102e-4132-8ecc-4e647b726109
		summarizeBy: none
		sourceColumn: job_key

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: dcb033c0-6b09-42a6-ad8c-4dfe828a049a
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column skill_key
		dataType: string
		lineageTag: 734a9070-5a5a-4176-9d3b-4210aecb45e3
		summarizeBy: none
		sourceColumn: skill_key

		annotation SummarizationSetBy = Automatic

	column Skill
		dataType: string
		lineageTag: acc17e50-635f-46e0-b224-5c80aca1e0b3
		summarizeBy: none
		sourceColumn: Skill

		annotation SummarizationSetBy = Automatic

	column mention = 1
		dataType: int64
		formatString: 0
		lineageTag: dd221b6f-1c2f-45bd-8a14-2b3eb8fc1af8
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition brdg__job_skill = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(AmazonAthena.Databases("Amazon Athena", null, []){[Kind="Database"]}[Data], "select#(lf)    distinct#(lf)    b.job_key,#(lf)    d.title,#(lf)    s.skill_key,#(lf)    s.skill#(lf)from brdg__job_skill b join dim__skill s on s.skill_key = b.skill_key#(lf)join fct__job_listing f on f.job_key = b.job_key#(lf)join dim__job_description d on d.job_description_key=f.job_description_key", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"skill", "Skill"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

