version: '3'

services:

  postgres:
    image: postgres:10.4
    env_file:
      - .env
    volumes:
      - postgres_local:/var/lib/postgresql/data
    ports:
      - 5432:5432

  webserver:
    image: airflow:latest
    env_file:
      - .env
    restart: always
    build: .
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./tests:/usr/local/airflow/tests
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    image: airflow:latest
    env_file:
      - .env
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./tests:/usr/local/airflow/tests
    command: scheduler

volumes:
  postgres_local: